version: '3.9'

services:
  webhook-app:
    image: webhook-app:latest
    container_name: webhook-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-webhook_user}
      DB_PASSWORD: ${DB_PASSWORD:-webhook_password}
      DB_NAME: ${DB_NAME:-webhook_db}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-60000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-*}
      API_KEY: ${API_KEY:-change-this-in-production}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    networks:
      - webhook-network
    volumes:
      - ./logs:/app/logs

networks:
  webhook-network:
    driver: bridge