name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build App and Push Image'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: docker login "${{ secrets.DOCKER_REGISTRY_URL }}" -u "${{ secrets.DOCKER_REGISTRY_KEY }}" -p "${{secrets.DOCKER_REGISTRY_KEY}}"

      - name: Build Docker Image
        run: docker build -t "${{ secrets.DOCKER_REGISTRY_URL }}/webhook-app" .

      - name: Push Docker Image to Registry
        run: docker push "${{ secrets.DOCKER_REGISTRY_URL }}/webhook-app"

      - name: Logout from Registry
        run: docker logout